export interface RivalLevel {
  level: number;
  name: string;
  title: string;
  avatar: string;
  color: string;
  targetTasks: number;
  targetFocusMinutes: number;
  targetHabitPct: number;
  rewardGold: number;
  rewardXp: number;
  quote: string;
  difficulty: 'FÁCIL' | 'MEDIO' | 'DIFÍCIL' | 'ÉPICO' | 'LEGENDARIO' | 'TITÁN';
  workStartHour?: number;
  workEndHour?: number;
  workStartMinute?: number;
  workEndMinute?: number;
}

export const RIVAL_LEVELS: RivalLevel[] = [
  {
    level: 1,
    name: 'Bruce Lee',
    title: 'El Dragón Invicto',
    avatar: '🥋',
    color: '#EF4444',
    targetTasks: 1,
    targetFocusMinutes: 60,
    targetHabitPct: 25,
    rewardGold: 25,
    rewardXp: 35,
    quote: 'No temo al hombre que ha practicado 10,000 patadas una vez, sino al que ha practicado una patada 10,000 veces.',
    difficulty: 'FÁCIL',
    workStartHour: 8,
    workEndHour: 17
  },
  {
    level: 2,
    name: 'Kobe Bryant',
    title: 'La Mentalidad Mamba',
    avatar: '🐍',
    color: '#8B5CF6',
    targetTasks: 1,
    targetFocusMinutes: 90,
    targetHabitPct: 30,
    rewardGold: 30,
    rewardXp: 45,
    quote: 'Lo más importante es intentar inspirar a las personas para que puedan ser excelentes en lo que quieran hacer.',
    difficulty: 'FÁCIL',
    workStartHour: 7,
    workEndHour: 18
  },
  {
    level: 3,
    name: 'Michael Jordan',
    title: 'La Leyenda Voladora',
    avatar: '🏀',
    color: '#3B82F6',
    targetTasks: 2,
    targetFocusMinutes: 120,
    targetHabitPct: 35,
    rewardGold: 35,
    rewardXp: 55,
    quote: 'He fallado más de 9,000 tiros en mi carrera. Por eso he tenido éxito.',
    difficulty: 'FÁCIL',
    workStartHour: 8,
    workEndHour: 18
  },
  {
    level: 4,
    name: 'Muhammad Ali',
    title: 'El Más Grande de Todos los Tiempos',
    avatar: '🥊',
    color: '#10B981',
    targetTasks: 2,
    targetFocusMinutes: 150,
    targetHabitPct: 40,
    rewardGold: 40,
    rewardXp: 65,
    quote: 'Odié cada minuto de entrenamiento, pero me dije: No te rindas. Sufre ahora y vive el resto de tu vida como un campeón.',
    difficulty: 'MEDIO',
    workStartHour: 7,
    workEndHour: 17
  },
  {
    level: 5,
    name: 'Cristiano Ronaldo',
    title: 'La Máquina de Rendimiento',
    avatar: '⚽',
    color: '#F59E0B',
    targetTasks: 2,
    targetFocusMinutes: 180,
    targetHabitPct: 45,
    rewardGold: 50,
    rewardXp: 80,
    quote: 'El talento sin trabajo duro no es absolutamente nada.',
    difficulty: 'MEDIO',
    workStartHour: 6,
    workEndHour: 19
  },
  {
    level: 6,
    name: 'Lionel Messi',
    title: 'El Genio Silencioso',
    avatar: '🔟',
    color: '#06B6D4',
    targetTasks: 3,
    targetFocusMinutes: 210,
    targetHabitPct: 50,
    rewardGold: 55,
    rewardXp: 90,
    quote: 'Me tomó 17 años y 114 días lograr mi éxito de la noche a la mañana.',
    difficulty: 'MEDIO',
    workStartHour: 8,
    workEndHour: 18
  },
  {
    level: 7,
    name: 'David Goggins',
    title: 'El Titán Imparable',
    avatar: '🔥',
    color: '#DC2626',
    targetTasks: 3,
    targetFocusMinutes: 240,
    targetHabitPct: 55,
    rewardGold: 60,
    rewardXp: 100,
    quote: 'Cuando tu mente te dice que terminaste, solo estás al 40% de tu capacidad real.',
    difficulty: 'MEDIO',
    workStartHour: 4,
    workEndHour: 20
  },
  {
    level: 8,
    name: 'Arnold Schwarzenegger',
    title: 'El Conquistador de Hierro',
    avatar: '🏋️',
    color: '#F43F5E',
    targetTasks: 3,
    targetFocusMinutes: 270,
    targetHabitPct: 60,
    rewardGold: 65,
    rewardXp: 110,
    quote: 'La resistencia con la que luchas en el gimnasio y en la vida es lo que construye un carácter fuerte.',
    difficulty: 'MEDIO',
    workStartHour: 6,
    workEndHour: 19
  },
  {
    level: 9,
    name: 'Iron Mike Tyson',
    title: 'Fuerza Devastadora',
    avatar: '🥊',
    color: '#9333EA',
    targetTasks: 4,
    targetFocusMinutes: 300,
    targetHabitPct: 62,
    rewardGold: 70,
    rewardXp: 120,
    quote: 'La disciplina es hacer lo que odias como si lo amaras.',
    difficulty: 'DIFÍCIL',
    workStartHour: 5,
    workEndHour: 18
  },
  {
    level: 10,
    name: 'Elon Musk',
    title: 'El Ingeniero Estelar',
    avatar: '🚀',
    color: '#E11D48',
    targetTasks: 4,
    targetFocusMinutes: 330,
    targetHabitPct: 65,
    rewardGold: 80,
    rewardXp: 135,
    quote: 'Trabaja como un demonio. Si otros ponen 40 horas y tú pones 100, lograrás en 4 meses lo que a ellos les toma un año.',
    difficulty: 'DIFÍCIL',
    workStartHour: 6,
    workEndHour: 22
  },
  {
    level: 11,
    name: 'Steve Jobs',
    title: 'El Visionario Disruptivo',
    avatar: '📱',
    color: '#38BDF8',
    targetTasks: 4,
    targetFocusMinutes: 360,
    targetHabitPct: 68,
    rewardGold: 90,
    rewardXp: 150,
    quote: 'Tu tiempo es limitado, no lo malgastes viviendo la vida de otro.',
    difficulty: 'DIFÍCIL',
    workStartHour: 7,
    workEndHour: 20
  },
  {
    level: 12,
    name: 'Nikola Tesla',
    title: 'El Domador del Rayo',
    avatar: '⚡',
    color: '#8B5CF6',
    targetTasks: 5,
    targetFocusMinutes: 390,
    targetHabitPct: 70,
    rewardGold: 100,
    rewardXp: 165,
    quote: 'El presente es de ellos; el futuro, por el que realmente trabajé, es mío.',
    difficulty: 'DIFÍCIL',
    workStartHour: 6,
    workEndHour: 22
  },
  {
    level: 13,
    name: 'Thomas Edison',
    title: 'El Mago de Menlo Park',
    avatar: '💡',
    color: '#EAB308',
    targetTasks: 5,
    targetFocusMinutes: 420,
    targetHabitPct: 72,
    rewardGold: 110,
    rewardXp: 180,
    quote: 'El genio es 1% inspiración y 99% transpiración e insistencia.',
    difficulty: 'DIFÍCIL',
    workStartHour: 7,
    workEndHour: 21
  },
  {
    level: 14,
    name: 'Albert Einstein',
    title: 'La Mente Cósmica',
    avatar: '🧠',
    color: '#10B981',
    targetTasks: 5,
    targetFocusMinutes: 450,
    targetHabitPct: 75,
    rewardGold: 120,
    rewardXp: 200,
    quote: 'La monotonía y la soledad de una vida tranquila estimulan la mente creadora.',
    difficulty: 'ÉPICO',
    workStartHour: 8,
    workEndHour: 19
  },
  {
    level: 15,
    name: 'Leonardo da Vinci',
    title: 'El Polímata Absoluto',
    avatar: '🎨',
    color: '#F97316',
    targetTasks: 6,
    targetFocusMinutes: 480,
    targetHabitPct: 78,
    rewardGold: 135,
    rewardXp: 225,
    quote: 'La simplicidad es la máxima sofisticación del ingenio humano.',
    difficulty: 'ÉPICO',
    workStartHour: 7,
    workEndHour: 21
  },
  {
    level: 16,
    name: 'Marcus Aurelius',
    title: 'El Emperador Estoico',
    avatar: '🏛️',
    color: '#D97706',
    targetTasks: 6,
    targetFocusMinutes: 510,
    targetHabitPct: 80,
    rewardGold: 150,
    rewardXp: 250,
    quote: 'Tienes poder sobre tu mente, no sobre los acontecimientos externos. Date cuenta de esto y hallarás la fuerza.',
    difficulty: 'ÉPICO',
    workStartHour: 5,
    workEndHour: 20
  },
  {
    level: 17,
    name: 'Seneca',
    title: 'El Sabio del Tiempo',
    avatar: '⏳',
    color: '#6366F1',
    targetTasks: 6,
    targetFocusMinutes: 540,
    targetHabitPct: 82,
    rewardGold: 165,
    rewardXp: 275,
    quote: 'No es que tengamos poco tiempo, sino que perdemos mucho.',
    difficulty: 'ÉPICO',
    workStartHour: 6,
    workEndHour: 19
  },
  {
    level: 18,
    name: 'Benjamin Franklin',
    title: 'El Fundador Disciplinado',
    avatar: '📜',
    color: '#3B82F6',
    targetTasks: 7,
    targetFocusMinutes: 570,
    targetHabitPct: 85,
    rewardGold: 180,
    rewardXp: 300,
    quote: 'La diligencia incesante es la verdadera madre de la buena suerte.',
    difficulty: 'ÉPICO',
    workStartHour: 5,
    workEndHour: 21
  },
  {
    level: 19,
    name: 'Winston Churchill',
    title: 'El León Inflexible',
    avatar: '🦁',
    color: '#B45309',
    targetTasks: 7,
    targetFocusMinutes: 600,
    targetHabitPct: 88,
    rewardGold: 200,
    rewardXp: 330,
    quote: 'Si estás atravesando el infierno, sigue caminando sin detenerte.',
    difficulty: 'LEGENDARIO',
    workStartHour: 7,
    workEndHour: 22
  },
  {
    level: 20,
    name: 'Miyamoto Musashi',
    title: 'El Espadachín Invicto',
    avatar: '⚔️',
    color: '#EF4444',
    targetTasks: 7,
    targetFocusMinutes: 630,
    targetHabitPct: 90,
    rewardGold: 220,
    rewardXp: 360,
    quote: 'Percibe aquello que no puede ser visto a simple vista. Domínate antes de pretender dominar el mundo.',
    difficulty: 'LEGENDARIO',
    workStartHour: 4,
    workEndHour: 20
  },
  {
    level: 21,
    name: 'Sun Tzu',
    title: 'El Estratega Supremo',
    avatar: '📜',
    color: '#059669',
    targetTasks: 8,
    targetFocusMinutes: 660,
    targetHabitPct: 92,
    rewardGold: 240,
    rewardXp: 390,
    quote: 'La máxima victoria es aquella que se gana antes de entrar en batalla.',
    difficulty: 'LEGENDARIO',
    workStartHour: 5,
    workEndHour: 21
  },
  {
    level: 22,
    name: 'Julius Caesar',
    title: 'El Imperator de Roma',
    avatar: '⚔️',
    color: '#C026D3',
    targetTasks: 8,
    targetFocusMinutes: 690,
    targetHabitPct: 94,
    rewardGold: 260,
    rewardXp: 420,
    quote: 'Veni, vidi, vici. Vine, vi y conquisté.',
    difficulty: 'LEGENDARIO',
    workStartHour: 6,
    workEndHour: 22
  },
  {
    level: 23,
    name: 'Alejandro Magno',
    title: 'El Conquistador de Mundos',
    avatar: '👑',
    color: '#D97706',
    targetTasks: 8,
    targetFocusMinutes: 720,
    targetHabitPct: 95,
    rewardGold: 280,
    rewardXp: 450,
    quote: 'No hay nada imposible para aquel que se atreve a intentarlo con fe inquebrantable.',
    difficulty: 'LEGENDARIO',
    workStartHour: 5,
    workEndHour: 22
  },
  {
    level: 24,
    name: 'Napoleon Bonaparte',
    title: 'El Emperador de Europa',
    avatar: '🪖',
    color: '#2563EB',
    targetTasks: 9,
    targetFocusMinutes: 750,
    targetHabitPct: 96,
    rewardGold: 300,
    rewardXp: 480,
    quote: 'Imposible es una palabra que solo se encuentra en el diccionario de los necios.',
    difficulty: 'TITÁN',
    workStartHour: 5,
    workEndHour: 23
  },
  {
    level: 25,
    name: 'Genghis Khan',
    title: 'El Titán de las Estepas',
    avatar: '🏹',
    color: '#7C3AED',
    targetTasks: 9,
    targetFocusMinutes: 780,
    targetHabitPct: 97,
    rewardGold: 330,
    rewardXp: 510,
    quote: 'Si tenías miedo, no lo hubieras hecho. Si lo hiciste, no tengas miedo.',
    difficulty: 'TITÁN',
    workStartHour: 5,
    workEndHour: 22
  },
  {
    level: 26,
    name: 'Carl Jung',
    title: 'El Explorador de la Mente',
    avatar: '👁️',
    color: '#0284C7',
    targetTasks: 9,
    targetFocusMinutes: 810,
    targetHabitPct: 98,
    rewardGold: 360,
    rewardXp: 540,
    quote: 'Quien mira hacia afuera, sueña; quien mira hacia adentro, despierta.',
    difficulty: 'TITÁN',
    workStartHour: 6,
    workEndHour: 21
  },
  {
    level: 27,
    name: 'Socrates',
    title: 'El Padre de la Sabiduría',
    avatar: '🏛️',
    color: '#059669',
    targetTasks: 10,
    targetFocusMinutes: 840,
    targetHabitPct: 98,
    rewardGold: 400,
    rewardXp: 580,
    quote: 'Una vida sin examen no merece ser vivida.',
    difficulty: 'TITÁN',
    workStartHour: 6,
    workEndHour: 20
  },
  {
    level: 28,
    name: 'Ragnar Lothbrok',
    title: 'El Conquistador del Norte',
    avatar: '🪓',
    color: '#DC2626',
    targetTasks: 10,
    targetFocusMinutes: 870,
    targetHabitPct: 99,
    rewardGold: 450,
    rewardXp: 620,
    quote: 'El poder solo se les da a aquellos que están dispuestos a bajar la cabeza para tomarlo.',
    difficulty: 'TITÁN',
    workStartHour: 5,
    workEndHour: 22
  },
  {
    level: 29,
    name: 'Ludwig van Beethoven',
    title: 'El Maestro Inquebrantable',
    avatar: '🎼',
    color: '#9333EA',
    targetTasks: 11,
    targetFocusMinutes: 900,
    targetHabitPct: 99,
    rewardGold: 500,
    rewardXp: 660,
    quote: 'Tocar una nota equivocada es insignificante. Tocar sin pasión es imperdonable.',
    difficulty: 'TITÁN',
    workStartHour: 6,
    workEndHour: 22
  },
  {
    level: 30,
    name: 'Alexander The Great Supreme',
    title: 'El Monarca Absoluto de la Gloria',
    avatar: '💎',
    color: '#EC4899',
    targetTasks: 12,
    targetFocusMinutes: 960,
    targetHabitPct: 100,
    rewardGold: 600,
    rewardXp: 750,
    quote: 'Has conquistado el mundo entero de la disciplina. Eres la cima indiscutible de la excelencia.',
    difficulty: 'TITÁN',
    workStartHour: 4,
    workEndHour: 23
  }
];
