export interface RivalLevel {
  level: number;
  name: string;
  title: string;
  avatar: string;
  color: string;
  targetTasks: number;
  targetFocusMinutes: number;
  targetHabitPct: number;
  rewardGold: number;
  rewardXp: number;
  quote: string;
  difficulty: 'FÁCIL' | 'MEDIO' | 'DIFÍCIL' | 'ÉPICO' | 'LEGENDARIO' | 'TITÁN';
}

export const RIVAL_LEVELS: RivalLevel[] = [
  {
    level: 1,
    name: 'Francesco Cirillo',
    title: 'Creador del Método Pomodoro',
    avatar: '⌛',
    color: '#EF4444',
    targetTasks: 1,
    targetFocusMinutes: 60,
    targetHabitPct: 25,
    rewardGold: 20,
    rewardXp: 30,
    quote: 'Cada 25 minutos de enfoque esculpen un futuro extraordinario.',
    difficulty: 'FÁCIL'
  },
  {
    level: 2,
    name: 'Tiago Forte',
    title: 'Arquitecto del Segundo Cerebro',
    avatar: '🧠',
    color: '#8B5CF6',
    targetTasks: 1,
    targetFocusMinutes: 90,
    targetHabitPct: 30,
    rewardGold: 25,
    rewardXp: 40,
    quote: 'Tu mente es para tener ideas, no para almacenarlas.',
    difficulty: 'FÁCIL'
  },
  {
    level: 3,
    name: 'Cal Newport',
    title: 'Maestro del Trabajo Profundo',
    avatar: '🎯',
    color: '#3B82F6',
    targetTasks: 2,
    targetFocusMinutes: 120,
    targetHabitPct: 35,
    rewardGold: 30,
    rewardXp: 50,
    quote: 'La capacidad de enfocarse sin distracción es la superpotencia del siglo XXI.',
    difficulty: 'FÁCIL'
  },
  {
    level: 4,
    name: 'David Allen',
    title: 'Creador de GTD (Getting Things Done)',
    avatar: '📋',
    color: '#10B981',
    targetTasks: 2,
    targetFocusMinutes: 150,
    targetHabitPct: 40,
    rewardGold: 35,
    rewardXp: 60,
    quote: 'Puedes hacer cualquier cosa, pero no todo al mismo tiempo.',
    difficulty: 'MEDIO'
  },
  {
    level: 5,
    name: 'Ryder Carroll',
    title: 'Diseñador del Bullet Journal',
    avatar: '📓',
    color: '#F59E0B',
    targetTasks: 2,
    targetFocusMinutes: 180,
    targetHabitPct: 45,
    rewardGold: 40,
    rewardXp: 70,
    quote: 'Rastrea el pasado, ordena el presente y diseña el futuro.',
    difficulty: 'MEDIO'
  },
  {
    level: 6,
    name: 'Tim Ferriss',
    title: 'El Experimentador de 4 Horas',
    avatar: '⏱️',
    color: '#06B6D4',
    targetTasks: 3,
    targetFocusMinutes: 210,
    targetHabitPct: 50,
    rewardGold: 45,
    rewardXp: 80,
    quote: 'El enfoque no es hacer más cosas, es hacer lo correcto con máximo impacto.',
    difficulty: 'MEDIO'
  },
  {
    level: 7,
    name: 'James Clear',
    title: 'Maestro de los Hábitos Atómicos',
    avatar: '⚛️',
    color: '#EC4899',
    targetTasks: 3,
    targetFocusMinutes: 240,
    targetHabitPct: 55,
    rewardGold: 50,
    rewardXp: 90,
    quote: 'No te elevas al nivel de tus metas, caes al nivel de tus sistemas.',
    difficulty: 'MEDIO'
  },
  {
    level: 8,
    name: 'Marie Kondo',
    title: 'La Ordenadora del Caos',
    avatar: '✨',
    color: '#F43F5E',
    targetTasks: 3,
    targetFocusMinutes: 270,
    targetHabitPct: 60,
    rewardGold: 55,
    rewardXp: 100,
    quote: 'El orden en tu entorno refleja la claridad inquebrantable de tu mente.',
    difficulty: 'MEDIO'
  },
  {
    level: 9,
    name: 'Mihaly Csikszentmihalyi',
    title: 'Pionero del Estado de Flujo',
    avatar: '🌊',
    color: '#6366F1',
    targetTasks: 4,
    targetFocusMinutes: 300,
    targetHabitPct: 62,
    rewardGold: 60,
    rewardXp: 110,
    quote: 'En el flujo perfecto, el tiempo desaparece y la maestría emerge.',
    difficulty: 'DIFÍCIL'
  },
  {
    level: 10,
    name: 'Charles Duhigg',
    title: 'Investigador de la Ciencia del Hábito',
    avatar: '🔄',
    color: '#14B8A6',
    targetTasks: 4,
    targetFocusMinutes: 330,
    targetHabitPct: 65,
    rewardGold: 65,
    rewardXp: 120,
    quote: 'La clave para transformar tu vida es dominar el bucle del hábito.',
    difficulty: 'DIFÍCIL'
  },
  {
    level: 11,
    name: 'Benjamin Franklin',
    title: 'El Fundador Disciplinado',
    avatar: '📜',
    color: '#3B82F6',
    targetTasks: 4,
    targetFocusMinutes: 360,
    targetHabitPct: 68,
    rewardGold: 70,
    rewardXp: 135,
    quote: 'La diligencia es la madre de la buena suerte.',
    difficulty: 'DIFÍCIL'
  },
  {
    level: 12,
    name: 'Thomas Edison',
    title: 'El Mago de Menlo Park',
    avatar: '💡',
    color: '#EAB308',
    targetTasks: 5,
    targetFocusMinutes: 390,
    targetHabitPct: 70,
    rewardGold: 75,
    rewardXp: 150,
    quote: 'El genio es 1% inspiración y 99% transpiración.',
    difficulty: 'DIFÍCIL'
  },
  {
    level: 13,
    name: 'Nikola Tesla',
    title: 'El Domador del Rayo',
    avatar: '⚡',
    color: '#8B5CF6',
    targetTasks: 5,
    targetFocusMinutes: 420,
    targetHabitPct: 72,
    rewardGold: 80,
    rewardXp: 165,
    quote: 'El presente es de ellos; el futuro, por el que trabajé, es mío.',
    difficulty: 'DIFÍCIL'
  },
  {
    level: 14,
    name: 'Leonardo da Vinci',
    title: 'El Polímata Absoluto',
    avatar: '🎨',
    color: '#F97316',
    targetTasks: 5,
    targetFocusMinutes: 450,
    targetHabitPct: 75,
    rewardGold: 90,
    rewardXp: 180,
    quote: 'La simplicidad es la máxima sofisticación.',
    difficulty: 'ÉPICO'
  },
  {
    level: 15,
    name: 'Isaac Newton',
    title: 'El Alquimista de la Fuerza',
    avatar: '🍎',
    color: '#10B981',
    targetTasks: 6,
    targetFocusMinutes: 480,
    targetHabitPct: 78,
    rewardGold: 100,
    rewardXp: 200,
    quote: 'Lo que sabemos es una gota; lo que ignoramos es un océano.',
    difficulty: 'ÉPICO'
  },
  {
    level: 16,
    name: 'Marcus Aurelius',
    title: 'El Emperador Estoico',
    avatar: '🏛️',
    color: '#D97706',
    targetTasks: 6,
    targetFocusMinutes: 510,
    targetHabitPct: 80,
    rewardGold: 110,
    rewardXp: 220,
    quote: 'Tienes poder sobre tu mente, no sobre los acontecimientos externos.',
    difficulty: 'ÉPICO'
  },
  {
    level: 17,
    name: 'Seneca',
    title: 'El Sabio del Tiempo',
    avatar: '⏳',
    color: '#6366F1',
    targetTasks: 6,
    targetFocusMinutes: 540,
    targetHabitPct: 82,
    rewardGold: 120,
    rewardXp: 240,
    quote: 'No es que tengamos poco tiempo, sino que perdemos mucho.',
    difficulty: 'ÉPICO'
  },
  {
    level: 18,
    name: 'Miyamoto Musashi',
    title: 'El Espadachín Invicto',
    avatar: '⚔️',
    color: '#EF4444',
    targetTasks: 7,
    targetFocusMinutes: 570,
    targetHabitPct: 85,
    rewardGold: 130,
    rewardXp: 260,
    quote: 'Percibe aquello que no puede ser visto a simple vista.',
    difficulty: 'ÉPICO'
  },
  {
    level: 19,
    name: 'Steve Jobs',
    title: 'El Visionario Disruptivo',
    avatar: '📱',
    color: '#38BDF8',
    targetTasks: 7,
    targetFocusMinutes: 600,
    targetHabitPct: 88,
    rewardGold: 140,
    rewardXp: 280,
    quote: 'Tu tiempo es limitado, no lo malgastes viviendo la vida de otro.',
    difficulty: 'LEGENDARIO'
  },
  {
    level: 20,
    name: 'Bill Gates',
    title: 'El Arquitecto del Código',
    avatar: '💻',
    color: '#0284C7',
    targetTasks: 7,
    targetFocusMinutes: 630,
    targetHabitPct: 90,
    rewardGold: 150,
    rewardXp: 300,
    quote: 'La paciencia y la disciplina continua garantizan el éxito.',
    difficulty: 'LEGENDARIO'
  },
  {
    level: 21,
    name: 'Jeff Bezos',
    title: 'El Impulsor del Día 1',
    avatar: '📦',
    color: '#F59E0B',
    targetTasks: 8,
    targetFocusMinutes: 660,
    targetHabitPct: 92,
    rewardGold: 165,
    rewardXp: 325,
    quote: 'Mantente siempre en el Día 1; el Día 2 es el estancamiento.',
    difficulty: 'LEGENDARIO'
  },
  {
    level: 22,
    name: 'Elon Musk',
    title: 'El Ingeniero Estelar',
    avatar: '🚀',
    color: '#E11D48',
    targetTasks: 8,
    targetFocusMinutes: 690,
    targetHabitPct: 94,
    rewardGold: 180,
    rewardXp: 350,
    quote: 'Trabaja el doble que los demás si quieres lograr lo imposible.',
    difficulty: 'LEGENDARIO'
  },
  {
    level: 23,
    name: 'David Goggins',
    title: 'El Titán Imparable',
    avatar: '🔥',
    color: '#DC2626',
    targetTasks: 8,
    targetFocusMinutes: 720,
    targetHabitPct: 95,
    rewardGold: 200,
    rewardXp: 375,
    quote: 'Cuando tu mente te dice que terminaste, solo estás al 40%.',
    difficulty: 'LEGENDARIO'
  },
  {
    level: 24,
    name: 'Kobe Bryant',
    title: 'La Mentalidad Mamba',
    avatar: '🐍',
    color: '#7C3AED',
    targetTasks: 9,
    targetFocusMinutes: 750,
    targetHabitPct: 96,
    rewardGold: 220,
    rewardXp: 400,
    quote: 'Descansaré al final, no en el medio.',
    difficulty: 'TITÁN'
  },
  {
    level: 25,
    name: 'Cristiano Ronaldo',
    title: 'La Máquina de Rendimiento',
    avatar: '⚽',
    color: '#2563EB',
    targetTasks: 9,
    targetFocusMinutes: 780,
    targetHabitPct: 97,
    rewardGold: 240,
    rewardXp: 425,
    quote: 'El talento sin trabajo duro no es nada.',
    difficulty: 'TITÁN'
  },
  {
    level: 26,
    name: 'Sun Tzu',
    title: 'El Estratega Supremo',
    avatar: '📜',
    color: '#059669',
    targetTasks: 9,
    targetFocusMinutes: 810,
    targetHabitPct: 98,
    rewardGold: 260,
    rewardXp: 450,
    quote: 'La máxima victoria es aquella que no requiere batalla.',
    difficulty: 'TITÁN'
  },
  {
    level: 27,
    name: 'Alejandro Magno',
    title: 'El Conquistador de Mundos',
    avatar: '👑',
    color: '#D97706',
    targetTasks: 10,
    targetFocusMinutes: 840,
    targetHabitPct: 98,
    rewardGold: 280,
    rewardXp: 475,
    quote: 'No hay nada imposible para aquel que se atreve a intentarlo.',
    difficulty: 'TITÁN'
  },
  {
    level: 28,
    name: 'Chronos',
    title: 'El Guardián del Tiempo Eterno',
    avatar: '⏳',
    color: '#A855F7',
    targetTasks: 10,
    targetFocusMinutes: 870,
    targetHabitPct: 99,
    rewardGold: 300,
    rewardXp: 500,
    quote: 'El tiempo todo lo devora, excepto la verdadera voluntad.',
    difficulty: 'TITÁN'
  },
  {
    level: 29,
    name: 'Odín',
    title: 'El Padre de Toda Sabiduría',
    avatar: '👁️',
    color: '#6366F1',
    targetTasks: 11,
    targetFocusMinutes: 900,
    targetHabitPct: 99,
    rewardGold: 325,
    rewardXp: 550,
    quote: 'Sacrifiqué el descanso por la visión y la maestría absoluta.',
    difficulty: 'TITÁN'
  },
  {
    level: 30,
    name: 'Lux Resilient',
    title: 'El Titán Supremo de la Matrix',
    avatar: '💎',
    color: '#EC4899',
    targetTasks: 12,
    targetFocusMinutes: 960,
    targetHabitPct: 100,
    rewardGold: 350,
    rewardXp: 600,
    quote: 'Has conquistado la ilusión de los límites. Eres el dueño absoluto de tu destino.',
    difficulty: 'TITÁN'
  }
];
