export const ICON_CATEGORIES: Record<string, string[]> = {
    'Esenciales': ['Star', 'Heart', 'Zap', 'Flame', 'Trophy', 'Target', 'Check', 'CheckCircle', 'Plus', 'X', 'Trash2', 'Edit2', 'Settings', 'Menu', 'Search', 'Filter', 'MoreHorizontal', 'AlertCircle', 'HelpCircle', 'Info', 'Hash', 'Grid', 'List', 'Maximize', 'Minimize', 'RefreshCw', 'Shield', 'ShieldCheck', 'Sparkles', 'Timer', 'ToggleLeft', 'ToggleRight', 'Eye', 'EyeOff', 'BellRing', 'BellOff'],
    'Salud': ['Activity', 'Pulse', 'Brain', 'Smile', 'Frown', 'Dumbbell', 'Bike', 'Footprints', 'Droplets', 'Moon', 'Sun', 'Apple', 'Coffee', 'Bed', 'Pill', 'Stethoscope', 'GlassWater', 'Salad', 'Carrot', 'HeartPulse', 'Scale', 'Bone', 'Syringe', 'Thermometer', 'Trees', 'Cigarette', 'Ban', 'BicepsFlexed', 'PersonStanding', 'TimerReset', 'Crosshair', 'Ear', 'Vegan', 'Wheat', 'Soup', 'FirstAid', 'HeartBeat'],
    'Mente': ['Brain', 'BrainCircuit', 'Flower', 'Flower2', 'Heart', 'Moon', 'MoonStar', 'Sun', 'SunMedium', 'Cloud', 'CloudRain', 'Wind', 'Smile', 'SmilePlus', 'Frown', 'Eye', 'Lightbulb', 'Feather', 'Ear', 'Compass', 'BookOpen'],
    'Cuerpo': ['BicepsFlexed', 'Dumbbell', 'PersonStanding', 'Activity', 'Droplets', 'Bath', 'ShowerHead', 'Scissors', 'Comb', 'Footprints', 'Shirt', 'Watch', 'GlassWater', 'Apple', 'Salad', 'Bed', 'BedSingle', 'BedDouble'],
    'Creatividad': ['Palette', 'PenTool', 'Pencil', 'Pen', 'Brush', 'Music', 'Mic', 'Camera', 'Video', 'Film', 'Image', 'Type', 'Wand2', 'Sparkles', 'Stars', 'Book', 'Feather'],
    'Rutina': ['Clock', 'Calendar', 'CalendarDays', 'CheckSquare', 'ListTodo', 'AlarmClock', 'Timer', 'Sunrise', 'Sunset', 'Moon', 'Coffee', 'Utensils', 'WashingMachine', 'Shirt', 'Trash', 'Broom', 'ShoppingCart'],
    'Amor': ['Heart', 'HeartHandshake', 'Users', 'UserPlus', 'Baby', 'Home', 'Gift', 'Smile', 'MessageCircle', 'PhoneCall', 'Flower2'],
    'Espiritualidad': ['Star', 'Stars', 'Moon', 'Sun', 'Flame', 'Feather', 'Wind', 'Cloud', 'Eye', 'Book', 'BookOpen', 'Hands', 'Heart', 'Sparkles', 'Compass', 'Infinity', 'Cross'],
    'Productividad': ['CheckSquare', 'List', 'Calendar', 'Clock', 'Award', 'Flag', 'Bookmark', 'FileText', 'Folder', 'Archive', 'Inbox', 'Mail', 'Send', 'Paperclip', 'Pin', 'Briefcase', 'Layers', 'Layout', 'Kanban', 'ListTodo', 'Network', 'PenTool', 'Table', 'ClipboardList', 'CalendarDays', 'FileSpreadsheet', 'GanttChartSquare', 'Target', 'Rocket', 'Focus', 'Compass', 'Hourglass', 'Wand2', 'Workflow'],
    'Finanzas': ['DollarSign', 'CreditCard', 'Wallet', 'PiggyBank', 'Banknote', 'Coins', 'TrendingUp', 'BarChart', 'PieChart', 'ShoppingBag', 'ShoppingCart', 'Tag', 'Gift', 'Percent', 'Receipt', 'Calculator', 'BadgeDollarSign', 'Bitcoin', 'CandlestickChart', 'CircleDollarSign', 'Gem', 'HandCoins', 'Landmark', 'LineChart', 'Scale3d', 'Vault', 'Briefcase', 'Building', 'TrendingDown', 'Gavel'],
    'Tecnología': ['Smartphone', 'Laptop', 'Monitor', 'Cpu', 'Wifi', 'Battery', 'Bluetooth', 'Headphones', 'Code', 'Terminal', 'Database', 'Server', 'Cloud', 'Keyboard', 'Mouse', 'Calculator', 'HardDrive', 'MemoryStick', 'Microscope', 'Plug', 'Printer', 'QrCode', 'Radio', 'Router', 'Save', 'Scan', 'Speaker', 'Tv', 'Usb', 'Webcam', 'Gamepad', 'Bot', 'Fingerprint'],
    'Educación': ['Book', 'BookOpen', 'GraduationCap', 'Library', 'Pencil', 'Pen', 'Lightbulb', 'Puzzle', 'BrainCircuit', 'School', 'Microscope', 'Telescope', 'Atom', 'Backpack', 'Calculator', 'Clipboard', 'Compass', 'Languages', 'Palette', 'ScrollText', 'Highlighter', 'Glasses', 'FlaskConical', 'Ruler', 'FileBadge', 'BookMarked'],
    'Hogar': ['Home', 'Key', 'Lock', 'Unlock', 'DoorOpen', 'Sofa', 'BedDouble', 'Bath', 'Utensils', 'Wine', 'ChefHat', 'Wrench', 'Hammer', 'Umbrella', 'Scissors', 'Armchair', 'Fan', 'Flashlight', 'Fridge', 'Lamp', 'Microwave', 'PaintRoller', 'Plant', 'ShowerHead', 'Thermometer', 'Trash', 'WashingMachine', 'Flower2', 'BedSingle', 'CoffeeMaker', 'Blinds'],
    'Comida': ['Apple', 'Banana', 'Carrot', 'Cherry', 'Citrus', 'Croissant', 'Grape', 'IceCream', 'NutOff', 'Pizza', 'Salad', 'Soup', 'Vegan', 'Wheat', 'Beer', 'Coffee', 'CupSoda', 'GlassWater', 'Martini', 'Wine', 'Beef', 'Cake', 'UtensilsCrossed', 'ChefHat'],
    'Viajes': ['Plane', 'Car', 'Bus', 'Train', 'Ship', 'Map', 'MapPin', 'Compass', 'Globe', 'Luggage', 'Ticket', 'Camera', 'Image', 'Mountain', 'Tent', 'Anchor', 'BaggageClaim', 'Caravan', 'Hotel', 'MapPinned', 'Palmtree', 'ParkingSquare', 'PlaneTakeoff', 'PlaneLanding', 'ShipWheel', 'Signpost', 'TramFront', 'TrainFront', 'BusFront', 'CarTaxiFront'],
    'Naturaleza': ['TreePine', 'TreeDeciduous', 'Trees', 'Leaf', 'Flower', 'Flower2', 'CloudSun', 'CloudRain', 'Snowflake', 'Wind', 'MountainSnow', 'SunMedium', 'MoonStar', 'Flame', 'Droplets', 'Bird', 'Bug', 'Cat', 'Dog', 'Fish', 'Rabbit', 'Snail', 'Turtle', 'Worm'],
    'Deportes': ['Trophy', 'Medal', 'Target', 'Crosshair', 'BicepsFlexed', 'Dumbbell', 'Timer', 'Activity', 'Bike', 'Swords', 'Flag', 'Goal', 'PersonStanding', 'TimerReset'],
    'Social': ['User', 'Users', 'UserPlus', 'MessageCircle', 'MessageSquare', 'Phone', 'Video', 'Mic', 'Music', 'Share2', 'ThumbsUp', 'HeartHandshake', 'PartyPopper', 'Baby', 'Bell', 'Camera', 'Cat', 'Dog', 'Gamepad2', 'Ghost', 'Gift', 'Heart', 'Mail', 'Podcast', 'Radio', 'Rss', 'Send', 'Smile', 'Speaker', 'Tv', 'Twitch', 'Twitter', 'Youtube', 'Instagram', 'Facebook', 'Linkedin', 'Github', 'ThumbsDown', 'HandMetal', 'Handshake']
};

export const ICON_KEYWORDS_ES: Record<string, string[]> = {
    // Esenciales
    'Star': ['estrella', 'favorito', 'destacado', 'importante', 'brillo'],
    'Heart': ['corazón', 'amor', 'salud', 'vida', 'favorito', 'me gusta'],
    'Zap': ['energía', 'rayo', 'rápido', 'flash', 'electricidad', 'acción'],
    'Flame': ['fuego', 'llama', 'racha', 'caliente', 'quemar', 'pasión'],
    'Trophy': ['trofeo', 'premio', 'victoria', 'ganar', 'logro', 'meta'],
    'Target': ['objetivo', 'diana', 'meta', 'foco', 'precisión', 'apuntar'],
    'Check': ['bien', 'listo', 'hecho', 'completado', 'correcto', 'aprobar'],
    'CheckCircle': ['círculo', 'bien', 'listo', 'completado', 'éxito'],
    'Plus': ['añadir', 'sumar', 'nuevo', 'crear', 'más', 'positivo'],
    'X': ['cerrar', 'cancelar', 'eliminar', 'no', 'error', 'cruz'],
    'Trash2': ['basura', 'eliminar', 'borrar', 'quitar', 'papelera', 'tacho'],
    'Edit2': ['editar', 'lápiz', 'escribir', 'modificar', 'cambiar'],
    'Settings': ['configuración', 'ajustes', 'engranaje', 'opciones', 'tuerca'],
    'Menu': ['menú', 'hamburguesa', 'lista', 'opciones', 'navegación'],
    'Search': ['buscar', 'lupa', 'encontrar', 'explorar', 'investigar'],
    'Filter': ['filtro', 'filtrar', 'embudo', 'ordenar', 'seleccionar'],
    'MoreHorizontal': ['más', 'opciones', 'puntos', 'extra'],
    'AlertCircle': ['alerta', 'peligro', 'atención', 'advertencia', 'cuidado'],
    'HelpCircle': ['ayuda', 'pregunta', 'duda', 'información', 'soporte'],
    'Info': ['información', 'detalle', 'datos', 'saber', 'acerca de'],
    'Sparkles': ['brillos', 'magia', 'nuevo', 'limpio', 'estrellas', 'destello'],
    'Shield': ['escudo', 'seguridad', 'protección', 'defensa', 'guardar'],
    'Eye': ['ojo', 'ver', 'mirar', 'visión', 'mostrar', 'observar'],
    'EyeOff': ['ocultar', 'ciego', 'invisible', 'privado', 'esconder'],
    'BellRing': ['campana', 'sonar', 'notificación', 'alarma', 'aviso', 'despertar'],
    'BellOff': ['silencio', 'mudo', 'sin sonido', 'no molestar', 'apagar'],
    
    // Salud
    'Activity': ['actividad', 'pulso', 'salud', 'ritmo', 'movimiento', 'ejercicio'],
    'Pulse': ['pulso', 'salud', 'corazón', 'vida', 'latido'],
    'Brain': ['cerebro', 'mente', 'pensar', 'inteligencia', 'psicología', 'mental'],
    'Smile': ['feliz', 'sonrisa', 'alegría', 'emoción', 'bienestar', 'cara'],
    'SmilePlus': ['feliz', 'sonrisa', 'alegría', 'emoción', 'bienestar', 'cara', 'mas'],
    'Frown': ['triste', 'mal', 'emoción', 'cara', 'depresión'],
    'Dumbbell': ['pesa', 'gimnasio', 'gym', 'fuerza', 'entrenamiento', 'músculo', 'fitness', 'levantar', 'ejercicio'],
    'BicepsFlexed': ['músculo', 'brazo', 'fuerza', 'gym', 'gimnasio', 'poder', 'fuerte'],
    'Bike': ['bicicleta', 'bici', 'ciclismo', 'cardio', 'ejercicio', 'pedalear', 'transporte'],
    'Footprints': ['pasos', 'caminar', 'huellas', 'pies', 'andar', 'paseo', 'caminata'],
    'Droplets': ['agua', 'gotas', 'hidratación', 'beber', 'líquido', 'sudor'],
    'Moon': ['luna', 'noche', 'dormir', 'sueño', 'descanso', 'oscuro'],
    'Sun': ['sol', 'día', 'mañana', 'luz', 'despertar', 'brillo'],
    'Apple': ['manzana', 'fruta', 'comida', 'dieta', 'saludable', 'nutrición'],
    'Coffee': ['café', 'taza', 'desayuno', 'bebida', 'energía', 'mañana', 'despertar'],
    'Bed': ['cama', 'dormir', 'sueño', 'descanso', 'noche', 'habitación'],
    'Pill': ['pastilla', 'medicina', 'medicamento', 'salud', 'curar', 'tratamiento', 'vitamina'],
    'Stethoscope': ['médico', 'doctor', 'salud', 'hospital', 'revisión', 'clínica'],
    'GlassWater': ['agua', 'vaso', 'beber', 'hidratación', 'sed', 'líquido'],
    'Salad': ['ensalada', 'verdura', 'comida', 'saludable', 'dieta', 'vegano', 'nutrición'],
    'Carrot': ['zanahoria', 'verdura', 'comida', 'saludable', 'dieta', 'vegetal'],
    'HeartPulse': ['corazón', 'pulso', 'salud', 'cardio', 'latido', 'vida'],
    'Scale': ['báscula', 'peso', 'pesar', 'dieta', 'medida', 'balanza'],
    'Bone': ['hueso', 'calcio', 'esqueleto', 'perro', 'cuerpo'],
    'Syringe': ['jeringa', 'vacuna', 'inyección', 'sangre', 'medicina', 'doctor'],
    'Thermometer': ['termómetro', 'temperatura', 'fiebre', 'calor', 'frío', 'enfermo'],
    'Cigarette': ['cigarro', 'fumar', 'tabaco', 'vicio', 'mal hábito'],
    'Ban': ['prohibido', 'no', 'detener', 'bloquear', 'cancelar', 'parar'],
    'PersonStanding': ['persona', 'de pie', 'humano', 'postura', 'cuerpo', 'estiramiento'],
    'Crosshair': ['mira', 'apuntar', 'precisión', 'foco', 'objetivo', 'concentración'],
    'Ear': ['oreja', 'escuchar', 'oído', 'audición', 'sonido'],
    'Vegan': ['vegano', 'planta', 'hoja', 'saludable', 'dieta', 'naturaleza'],
    'Wheat': ['trigo', 'cereal', 'pan', 'comida', 'gluten', 'cosecha'],
    'Soup': ['sopa', 'comida', 'caliente', 'plato', 'almuerzo'],
    'FirstAid': ['primeros auxilios', 'botiquín', 'cruz', 'salud', 'emergencia', 'médico'],
    'HeartBeat': ['latido', 'corazón', 'pulso', 'vida', 'salud', 'cardio'],

    // Nuevos
    'Feather': ['pluma', 'ligero', 'escribir', 'pájaro', 'volar', 'suave'],
    'Comb': ['peine', 'pelo', 'cabello', 'belleza', 'cuidado'],
    'Shirt': ['camisa', 'ropa', 'vestir', 'lavar', 'moda'],
    'Watch': ['reloj', 'pulsera', 'tiempo', 'moda', 'accesorio'],
    'Brush': ['pincel', 'pintar', 'arte', 'creativo', 'dibujo'],
    'Film': ['película', 'cine', 'video', 'cámara', 'grabar'],
    'Type': ['texto', 'escribir', 'letra', 'fuente', 'tipografía'],
    'AlarmClock': ['alarma', 'reloj', 'despertar', 'tiempo', 'mañana'],
    'Sunrise': ['amanecer', 'mañana', 'sol', 'día', 'despertar'],
    'Sunset': ['atardecer', 'tarde', 'sol', 'noche', 'ocaso'],
    'Broom': ['escoba', 'barrer', 'limpiar', 'casa', 'hogar'],
    'PhoneCall': ['llamar', 'teléfono', 'hablar', 'comunicación'],
    'Hands': ['manos', 'ayuda', 'oración', 'paz', 'dar'],
    'Infinity': ['infinito', 'siempre', 'eternidad', 'ciclo'],
    'Cross': ['cruz', 'religión', 'fe', 'iglesia', 'salud'],

    // Productividad
    'CheckSquare': ['tarea', 'lista', 'hecho', 'completar', 'casilla', 'todo'],
    'List': ['lista', 'tareas', 'ítems', 'viñetas', 'orden'],
    'Calendar': ['calendario', 'fecha', 'día', 'mes', 'año', 'agenda', 'plan', 'evento'],
    'Clock': ['reloj', 'tiempo', 'hora', 'minuto', 'alarma', 'retraso', 'espera'],
    'Award': ['premio', 'medalla', 'logro', 'ganador', 'victoria', 'reconocimiento'],
    'Flag': ['bandera', 'meta', 'marca', 'hito', 'objetivo', 'destino'],
    'Bookmark': ['marcador', 'guardar', 'favorito', 'leer', 'libro'],
    'FileText': ['archivo', 'texto', 'documento', 'papel', 'nota'],
    'Folder': ['carpeta', 'directorio', 'archivos', 'organizar', 'guardar'],
    'Archive': ['archivo', 'caja', 'guardar', 'historial', 'viejo'],
    'Inbox': ['bandeja', 'entrada', 'correo', 'recibir', 'mensajes'],
    'Mail': ['correo', 'carta', 'email', 'mensaje', 'sobre', 'enviar'],
    'Send': ['enviar', 'mandar', 'avión', 'papel', 'mensaje'],
    'Paperclip': ['clip', 'adjunto', 'archivo', 'unir', 'enlazar'],
    'Pin': ['pin', 'chincheta', 'fijar', 'marcar', 'ubicación', 'nota'],
    'Briefcase': ['maletín', 'trabajo', 'negocio', 'empleo', 'oficina', 'profesional'],
    'Layers': ['capas', 'niveles', 'pila', 'montón', 'organizar'],
    'Rocket': ['cohete', 'lanzamiento', 'inicio', 'rápido', 'espacio', 'impulso', 'startup'],
    'Layout': ['diseño', 'estructura', 'cuadrícula', 'panel', 'organización'],
    'Kanban': ['kanban', 'tablero', 'columnas', 'ágil', 'tareas', 'proyecto'],
    'ListTodo': ['tareas', 'pendientes', 'hacer', 'lista', 'checklist'],
    'Focus': ['foco', 'concentración', 'apuntar', 'centro', 'atención'],
    'Compass': ['brújula', 'dirección', 'guía', 'orientación', 'camino', 'norte'],
    'Hourglass': ['reloj de arena', 'tiempo', 'espera', 'cuenta regresiva', 'duración'],
    'Wand2': ['varita', 'magia', 'automático', 'crear', 'varita mágica', 'herramienta'],
    'Workflow': ['flujo', 'trabajo', 'proceso', 'pasos', 'diagrama', 'sistema'],

    // Finanzas
    'DollarSign': ['dólar', 'dinero', 'moneda', 'efectivo', 'pago', 'precio', 'costo'],
    'CreditCard': ['tarjeta', 'crédito', 'débito', 'pago', 'comprar', 'banco', 'plástico'],
    'Wallet': ['cartera', 'billetera', 'dinero', 'guardar', 'pago', 'efectivo'],
    'PiggyBank': ['cerdo', 'ahorro', 'dinero', 'banco', 'guardar', 'alcancía'],
    'Banknote': ['billete', 'dinero', 'efectivo', 'papel', 'pago'],
    'Coins': ['monedas', 'dinero', 'cambio', 'suelto', 'oro', 'plata'],
    'TrendingUp': ['tendencia', 'arriba', 'crecimiento', 'subir', 'mejora', 'gráfico', 'progreso'],
    'BarChart': ['gráfico', 'barras', 'datos', 'estadísticas', 'análisis'],
    'PieChart': ['gráfico', 'tarta', 'porción', 'porcentaje', 'datos'],
    'ShoppingBag': ['bolsa', 'compra', 'tienda', 'retail', 'mercado'],
    'ShoppingCart': ['carrito', 'compra', 'supermercado', 'tienda', 'ecommerce'],
    'Tag': ['etiqueta', 'precio', 'marca', 'categoría', 'nombre'],
    'Gift': ['regalo', 'presente', 'sorpresa', 'caja', 'donación', 'cumpleaños'],
    'Percent': ['porcentaje', 'descuento', 'oferta', 'rebaja', 'tasa'],
    'Receipt': ['recibo', 'factura', 'ticket', 'pago', 'comprobante', 'compra'],
    'Calculator': ['calculadora', 'matemáticas', 'sumar', 'cuentas', 'números', 'contabilidad'],
    'Bitcoin': ['bitcoin', 'cripto', 'criptomoneda', 'dinero', 'digital', 'inversión'],
    'Vault': ['bóveda', 'caja fuerte', 'seguro', 'banco', 'guardar', 'protección'],
    'Building': ['edificio', 'empresa', 'corporación', 'banco', 'oficina'],
    'TrendingDown': ['tendencia', 'abajo', 'caída', 'bajar', 'pérdida', 'gráfico'],
    'Gavel': ['martillo', 'juez', 'ley', 'justicia', 'legal', 'subasta'],

    // Tecnología
    'Smartphone': ['teléfono', 'móvil', 'celular', 'pantalla', 'llamar', 'app'],
    'Laptop': ['portátil', 'ordenador', 'computadora', 'pc', 'trabajo', 'tecnología'],
    'Monitor': ['pantalla', 'ordenador', 'pc', 'computadora', 'display'],
    'Cpu': ['procesador', 'chip', 'cerebro', 'hardware', 'ordenador'],
    'Wifi': ['wifi', 'internet', 'conexión', 'red', 'señal', 'inalámbrico'],
    'Battery': ['batería', 'energía', 'carga', 'pila', 'poder'],
    'Bluetooth': ['bluetooth', 'conexión', 'inalámbrico', 'dispositivo', 'emparejar'],
    'Headphones': ['auriculares', 'cascos', 'música', 'escuchar', 'audio', 'sonido'],
    'Code': ['código', 'programar', 'desarrollo', 'software', 'html', 'etiquetas'],
    'Terminal': ['consola', 'terminal', 'comandos', 'código', 'programar', 'cmd'],
    'Database': ['base de datos', 'servidor', 'almacenamiento', 'datos', 'sql'],
    'Server': ['servidor', 'red', 'hosting', 'computadora', 'datos'],
    'Cloud': ['nube', 'internet', 'almacenamiento', 'online', 'clima'],
    'Keyboard': ['teclado', 'escribir', 'teclas', 'ordenador', 'pc'],
    'Mouse': ['ratón', 'mouse', 'click', 'ordenador', 'pc', 'puntero'],
    'Gamepad': ['mando', 'juego', 'consola', 'videojuego', 'jugar', 'gamer'],
    'Bot': ['robot', 'bot', 'IA', 'inteligencia', 'máquina', 'autómata'],
    'Fingerprint': ['huella', 'seguridad', 'biometría', 'identidad', 'tocar'],

    // Educación
    'Book': ['libro', 'leer', 'estudio', 'lectura', 'aprender', 'novela'],
    'BookOpen': ['libro abierto', 'leer', 'estudio', 'aprender', 'educación'],
    'GraduationCap': ['graduación', 'universidad', 'escuela', 'colegio', 'estudio', 'título'],
    'Library': ['biblioteca', 'libros', 'estudio', 'leer', 'edificio', 'aprender'],
    'Pencil': ['lápiz', 'escribir', 'dibujar', 'apuntar', 'borrador'],
    'Pen': ['bolígrafo', 'pluma', 'escribir', 'firmar', 'tinta'],
    'Lightbulb': ['bombilla', 'idea', 'luz', 'pensar', 'creación', 'innovación', 'inspiración'],
    'Puzzle': ['rompecabezas', 'juego', 'pieza', 'solución', 'lógica', 'encajar'],
    'BrainCircuit': ['cerebro', 'inteligencia', 'IA', 'tecnología', 'mente', 'pensar'],
    'School': ['escuela', 'colegio', 'edificio', 'estudio', 'aprender', 'educación'],
    'Microscope': ['microscopio', 'ciencia', 'investigación', 'laboratorio', 'biología'],
    'Telescope': ['telescopio', 'estrellas', 'espacio', 'ciencia', 'observar', 'astronomía'],
    'Atom': ['átomo', 'ciencia', 'física', 'química', 'núcleo', 'electrón'],
    'Backpack': ['mochila', 'bolsa', 'escuela', 'viaje', 'cargar', 'equipaje'],
    'Languages': ['idiomas', 'lenguas', 'hablar', 'traducción', 'palabras', 'comunicación'],
    'Palette': ['paleta', 'pintura', 'arte', 'colores', 'dibujo', 'creativo'],
    'Ruler': ['regla', 'medir', 'matemáticas', 'geometría', 'dibujo', 'tamaño'],
    'FileBadge': ['certificado', 'diploma', 'logro', 'archivo', 'premio', 'documento'],
    'BookMarked': ['libro marcado', 'estudiar', 'marcador', 'leer', 'aprender'],

    // Hogar
    'Home': ['casa', 'hogar', 'edificio', 'residencia', 'vivienda', 'inicio'],
    'Key': ['llave', 'cerradura', 'puerta', 'abrir', 'seguridad', 'acceso'],
    'Lock': ['candado', 'cerrado', 'bloqueado', 'seguro', 'privado', 'contraseña'],
    'Unlock': ['abierto', 'desbloqueado', 'candado', 'acceso', 'libre'],
    'DoorOpen': ['puerta', 'abrir', 'entrar', 'salir', 'habitación', 'casa'],
    'Sofa': ['sofá', 'mueble', 'descanso', 'sala', 'salón', 'asiento'],
    'BedDouble': ['cama', 'doble', 'dormir', 'pareja', 'habitación', 'sueño'],
    'Bath': ['bañera', 'baño', 'ducha', 'agua', 'limpiar', 'aseo'],
    'Utensils': ['cubiertos', 'tenedor', 'cuchillo', 'comida', 'comer', 'restaurante', 'cocina'],
    'Wine': ['vino', 'copa', 'bebida', 'alcohol', 'fiesta', 'celebración', 'brindar'],
    'ChefHat': ['chef', 'cocinero', 'sombrero', 'cocina', 'receta', 'comida'],
    'Wrench': ['llave inglesa', 'herramienta', 'reparar', 'arreglar', 'mecánico', 'taller'],
    'Hammer': ['martillo', 'herramienta', 'golpear', 'clavar', 'construcción', 'arreglar'],
    'Umbrella': ['paraguas', 'lluvia', 'clima', 'agua', 'proteger', 'tiempo'],
    'Scissors': ['tijeras', 'cortar', 'papel', 'herramienta', 'peluquería', 'manualidad'],
    'Plant': ['planta', 'hoja', 'naturaleza', 'crecer', 'verde', 'jardín', 'maceta'],
    'Trash': ['basura', 'tacho', 'eliminar', 'desecho', 'limpiar', 'papelera'],
    'BedSingle': ['cama individual', 'dormir', 'descanso', 'sueño', 'habitación'],
    'CoffeeMaker': ['cafetera', 'máquina', 'café', 'desayuno', 'cocina', 'bebida'],
    'Blinds': ['persianas', 'cortinas', 'ventana', 'luz', 'sombra', 'casa'],

    // Comida
    'Banana': ['plátano', 'banana', 'fruta', 'comida', 'dieta', 'potasio'],
    'Cherry': ['cereza', 'fruta', 'comida', 'dulce', 'rojo', 'postre'],
    'Citrus': ['cítrico', 'limón', 'naranja', 'fruta', 'ácido', 'jugo', 'vitamina'],
    'Croissant': ['croissant', 'pan', 'desayuno', 'comida', 'panadería', 'dulce'],
    'Grape': ['uva', 'fruta', 'comida', 'vino', 'racimo'],
    'IceCream': ['helado', 'postre', 'dulce', 'frío', 'verano', 'comida'],
    'NutOff': ['nuez', 'alergia', 'frutos secos', 'comida', 'salud', 'precaución'],
    'Pizza': ['pizza', 'comida', 'chatarra', 'italiana', 'queso', 'rebanada'],
    'Beer': ['cerveza', 'bebida', 'alcohol', 'bar', 'fiesta', 'trago'],
    'CupSoda': ['refresco', 'soda', 'bebida', 'vaso', 'hielo', 'pajita', 'comida'],
    'Martini': ['martini', 'cóctel', 'bebida', 'alcohol', 'fiesta', 'bar', 'trago'],
    'Beef': ['carne', 'bife', 'filete', 'proteína', 'comida', 'asado'],
    'Cake': ['pastel', 'torta', 'tarta', 'cumpleaños', 'dulce', 'postre', 'celebración'],
    'UtensilsCrossed': ['cubiertos', 'restaurante', 'comer', 'cenar', 'comida', 'cruzados'],

    // Viajes
    'Plane': ['avión', 'vuelo', 'viaje', 'aire', 'aeropuerto', 'volar'],
    'Car': ['coche', 'auto', 'carro', 'vehículo', 'conducir', 'viaje', 'motor'],
    'Bus': ['autobús', 'bus', 'transporte', 'público', 'viaje', 'ruta'],
    'Train': ['tren', 'ferrocarril', 'viaje', 'vía', 'estación', 'transporte'],
    'Ship': ['barco', 'bote', 'mar', 'agua', 'navegar', 'viaje', 'crucero'],
    'Map': ['mapa', 'dirección', 'ruta', 'camino', 'guía', 'ubicación'],
    'MapPin': ['pin', 'ubicación', 'lugar', 'marcador', 'destino', 'mapa'],
    'Globe': ['globo', 'mundo', 'tierra', 'planeta', 'internacional', 'países'],
    'Luggage': ['equipaje', 'maleta', 'viaje', 'vacaciones', 'bolsa', 'cargar'],
    'Ticket': ['billete', 'boleto', 'entrada', 'cine', 'concierto', 'viaje', 'pase'],
    'Camera': ['cámara', 'foto', 'fotografía', 'imagen', 'captura', 'lente'],
    'Image': ['imagen', 'foto', 'paisaje', 'cuadro', 'galería', 'visual'],
    'Mountain': ['montaña', 'naturaleza', 'pico', 'escalar', 'paisaje', 'roca'],
    'Tent': ['tienda', 'campaña', 'camping', 'naturaleza', 'dormir', 'afuera', 'acampada'],
    'Hotel': ['hotel', 'edificio', 'hospedaje', 'dormir', 'viaje', 'vacaciones'],
    'TrainFront': ['tren', 'metro', 'subte', 'viaje', 'transporte', 'público'],
    'BusFront': ['bus', 'autobús', 'transporte', 'público', 'viaje', 'ruta'],
    'CarTaxiFront': ['taxi', 'coche', 'auto', 'viaje', 'transporte', 'pasajero'],

    // Naturaleza
    'TreePine': ['pino', 'árbol', 'bosque', 'naturaleza', 'madera', 'planta'],
    'TreeDeciduous': ['árbol', 'hojas', 'naturaleza', 'bosque', 'planta', 'verde'],
    'Trees': ['árboles', 'bosque', 'naturaleza', 'parque', 'paisaje', 'plantas'],
    'Leaf': ['hoja', 'naturaleza', 'planta', 'verde', 'otoño', 'ecología'],
    'Flower': ['flor', 'naturaleza', 'planta', 'primavera', 'pétalo', 'jardín'],
    'Flower2': ['flor', 'rosa', 'naturaleza', 'planta', 'jardín', 'decoración'],
    'CloudSun': ['nube', 'sol', 'clima', 'tiempo', 'cielo', 'parcialmente nublado'],
    'CloudRain': ['lluvia', 'nube', 'agua', 'clima', 'tiempo', 'tormenta'],
    'Snowflake': ['nieve', 'copo', 'frío', 'invierno', 'hielo', 'congelar'],
    'Wind': ['viento', 'aire', 'clima', 'brisa', 'tormenta', 'soplar'],
    'MountainSnow': ['montaña', 'nieve', 'pico', 'escalar', 'invierno', 'naturaleza'],
    'SunMedium': ['sol', 'calor', 'brillo', 'día', 'clima', 'luz'],
    'MoonStar': ['luna', 'estrella', 'noche', 'cielo', 'sueño', 'espacio'],
    'Bird': ['pájaro', 'ave', 'volar', 'animal', 'mascota', 'naturaleza'],
    'Bug': ['bicho', 'insecto', 'error', 'animal', 'naturaleza', 'pequeño'],
    'Fish': ['pez', 'pescado', 'agua', 'mar', 'océano', 'animal', 'nadar'],
    'Rabbit': ['conejo', 'animal', 'mascota', 'saltar', 'rápido', 'zanahoria'],
    'Snail': ['caracol', 'lento', 'animal', 'bicho', 'concha'],
    'Turtle': ['tortuga', 'lento', 'animal', 'mar', 'agua', 'caparazón'],
    'Worm': ['gusano', 'lombriz', 'tierra', 'animal', 'bicho'],

    // Deportes
    'Medal': ['medalla', 'premio', 'ganador', 'victoria', 'logro', 'competencia'],
    'Swords': ['espadas', 'lucha', 'combate', 'juego', 'batalla', 'duelo'],
    'Goal': ['meta', 'gol', 'fútbol', 'objetivo', 'puntuación', 'deporte'],

    // Social
    'User': ['usuario', 'persona', 'perfil', 'cuenta', 'avatar', 'humano'],
    'Users': ['usuarios', 'personas', 'grupo', 'equipo', 'comunidad', 'amigos'],
    'UserPlus': ['añadir', 'usuario', 'amigo', 'invitar', 'nuevo', 'seguir'],
    'MessageCircle': ['mensaje', 'chat', 'hablar', 'comentario', 'burbuja', 'texto'],
    'MessageSquare': ['mensaje', 'chat', 'cuadrado', 'texto', 'comentario', 'hablar'],
    'Phone': ['teléfono', 'llamar', 'móvil', 'contacto', 'hablar', 'voz'],
    'Video': ['vídeo', 'cámara', 'grabar', 'película', 'reunión', 'llamada'],
    'Mic': ['micrófono', 'voz', 'grabar', 'audio', 'hablar', 'cantar', 'podcast'],
    'Music': ['música', 'nota', 'sonido', 'canción', 'escuchar', 'audio', 'melodía'],
    'Share2': ['compartir', 'red', 'enviar', 'difundir', 'conectar', 'enlace'],
    'ThumbsUp': ['like', 'me gusta', 'bien', 'aprobar', 'pulgar', 'positivo'],
    'HeartHandshake': ['corazón', 'manos', 'acuerdo', 'trato', 'amistad', 'ayuda', 'apoyo'],
    'PartyPopper': ['fiesta', 'celebración', 'confeti', 'alegría', 'evento', 'cumpleaños'],
    'Baby': ['bebé', 'niño', 'infantil', 'hijo', 'crianza', 'pequeño'],
    'Bell': ['campana', 'notificación', 'alerta', 'aviso', 'sonido', 'timbre'],
    'Cat': ['gato', 'mascota', 'animal', 'felino', 'michi'],
    'Dog': ['perro', 'mascota', 'animal', 'canino', 'cachorro'],
    'Gamepad2': ['juego', 'videojuego', 'consola', 'mando', 'jugar', 'gamer'],
    'ThumbsDown': ['dislike', 'no me gusta', 'mal', 'desaprobar', 'pulgar', 'negativo'],
    'HandMetal': ['mano', 'metal', 'rock', 'música', 'concierto', 'cuernos'],
    'Handshake': ['apretón de manos', 'trato', 'acuerdo', 'negocio', 'saludo', 'paz']
};

export const ICON_KEYWORDS_EN: Record<string, string[]> = {
    // Essentials
    'Star': ['star', 'favorite', 'featured', 'important', 'shine'],
    'Heart': ['heart', 'love', 'health', 'life', 'favorite', 'like'],
    'Zap': ['energy', 'lightning', 'fast', 'flash', 'electricity', 'action'],
    'Flame': ['fire', 'flame', 'streak', 'hot', 'burn', 'passion'],
    'Trophy': ['trophy', 'prize', 'victory', 'win', 'achievement', 'goal'],
    'Target': ['target', 'bullseye', 'goal', 'focus', 'precision', 'aim'],
    'Check': ['good', 'ready', 'done', 'completed', 'correct', 'approve'],
    'CheckCircle': ['circle', 'good', 'ready', 'completed', 'success'],
    'Plus': ['add', 'sum', 'new', 'create', 'more', 'positive'],
    'X': ['close', 'cancel', 'delete', 'no', 'error', 'cross'],
    'Trash2': ['trash', 'delete', 'erase', 'remove', 'bin', 'garbage'],
    'Edit2': ['edit', 'pencil', 'write', 'modify', 'change'],
    'Settings': ['settings', 'configuration', 'gear', 'options', 'nut'],
    'Menu': ['menu', 'hamburger', 'list', 'options', 'navigation'],
    'Search': ['search', 'magnifying glass', 'find', 'explore', 'investigate'],
    'Filter': ['filter', 'funnel', 'sort', 'select'],
    'MoreHorizontal': ['more', 'options', 'dots', 'extra'],
    'AlertCircle': ['alert', 'danger', 'attention', 'warning', 'careful'],
    'HelpCircle': ['help', 'question', 'doubt', 'information', 'support'],
    'Info': ['information', 'detail', 'data', 'know', 'about'],
    'Sparkles': ['sparkles', 'magic', 'new', 'clean', 'stars', 'flash'],
    'Shield': ['shield', 'security', 'protection', 'defense', 'save'],
    'Eye': ['eye', 'see', 'look', 'vision', 'show', 'observe'],
    'EyeOff': ['hide', 'blind', 'invisible', 'private', 'conceal'],
    'BellRing': ['bell', 'ring', 'notification', 'alarm', 'alert', 'wake'],
    'BellOff': ['silent', 'mute', 'no sound', 'do not disturb', 'off'],
    
    // Health
    'Activity': ['activity', 'pulse', 'health', 'rhythm', 'movement', 'exercise'],
    'Pulse': ['pulse', 'health', 'heart', 'life', 'beat'],
    'Brain': ['brain', 'mind', 'think', 'intelligence', 'psychology', 'mental'],
    'Smile': ['happy', 'smile', 'joy', 'emotion', 'wellness', 'face'],
    'SmilePlus': ['happy', 'smile', 'joy', 'emotion', 'wellness', 'face', 'plus'],
    'Frown': ['sad', 'bad', 'emotion', 'face', 'depression'],
    'Dumbbell': ['dumbbell', 'gym', 'strength', 'training', 'muscle', 'fitness', 'lift', 'exercise'],
    'BicepsFlexed': ['muscle', 'arm', 'strength', 'gym', 'power', 'strong'],
    'Bike': ['bicycle', 'bike', 'cycling', 'cardio', 'exercise', 'pedal', 'transport'],
    'Footprints': ['steps', 'walk', 'footprints', 'feet', 'stroll'],
    'Droplets': ['water', 'drops', 'hydration', 'drink', 'liquid', 'sweat'],
    'Moon': ['moon', 'night', 'sleep', 'rest', 'dark'],
    'Sun': ['sun', 'day', 'morning', 'light', 'wake up', 'shine'],
    'Apple': ['apple', 'fruit', 'food', 'diet', 'healthy', 'nutrition'],
    'Coffee': ['coffee', 'cup', 'breakfast', 'drink', 'energy', 'morning', 'wake up'],
    'Bed': ['bed', 'sleep', 'rest', 'night', 'room'],
    'Pill': ['pill', 'medicine', 'health', 'cure', 'treatment', 'vitamin'],
    'Stethoscope': ['doctor', 'medical', 'health', 'hospital', 'checkup', 'clinic'],
    'GlassWater': ['water', 'glass', 'drink', 'hydration', 'thirst', 'liquid'],
    'Salad': ['salad', 'vegetable', 'food', 'healthy', 'diet', 'vegan', 'nutrition'],
    'Carrot': ['carrot', 'vegetable', 'food', 'healthy', 'diet'],
    'HeartPulse': ['heart', 'pulse', 'health', 'cardio', 'beat', 'life'],
    'Scale': ['scale', 'weight', 'weigh', 'diet', 'measure', 'balance'],
    'Bone': ['bone', 'calcium', 'skeleton', 'dog', 'body'],
    'Syringe': ['syringe', 'vaccine', 'injection', 'blood', 'medicine', 'doctor'],
    'Thermometer': ['thermometer', 'temperature', 'fever', 'heat', 'cold', 'sick'],
    'Cigarette': ['cigarette', 'smoke', 'tobacco', 'vice', 'bad habit'],
    'Ban': ['banned', 'no', 'stop', 'block', 'cancel'],
    'PersonStanding': ['person', 'standing', 'human', 'posture', 'body', 'stretch'],
    'Crosshair': ['crosshair', 'aim', 'precision', 'focus', 'target', 'concentration'],
    'Ear': ['ear', 'listen', 'hearing', 'sound'],
    'Vegan': ['vegan', 'plant', 'leaf', 'healthy', 'diet', 'nature'],
    'Wheat': ['wheat', 'cereal', 'bread', 'food', 'gluten', 'harvest'],
    'Soup': ['soup', 'food', 'hot', 'dish', 'lunch'],
    'FirstAid': ['first aid', 'kit', 'cross', 'health', 'emergency', 'medical'],
    'HeartBeat': ['heartbeat', 'heart', 'pulse', 'life', 'health', 'cardio'],

    // New
    'Feather': ['feather', 'light', 'write', 'bird', 'fly', 'soft'],
    'Comb': ['comb', 'hair', 'beauty', 'care'],
    'Shirt': ['shirt', 'clothes', 'dress', 'wash', 'fashion'],
    'Watch': ['watch', 'bracelet', 'time', 'fashion', 'accessory'],
    'Brush': ['brush', 'paint', 'art', 'creative', 'drawing'],
    'Film': ['film', 'movie', 'video', 'camera', 'record'],
    'Type': ['text', 'write', 'letter', 'font', 'typography'],
    'AlarmClock': ['alarm', 'clock', 'wake', 'time', 'morning'],
    'Sunrise': ['sunrise', 'morning', 'sun', 'day', 'wake'],
    'Sunset': ['sunset', 'evening', 'sun', 'night', 'dusk'],
    'Broom': ['broom', 'sweep', 'clean', 'house', 'home'],
    'PhoneCall': ['call', 'phone', 'talk', 'communication'],
    'Hands': ['hands', 'help', 'pray', 'peace', 'give'],
    'Infinity': ['infinity', 'always', 'eternity', 'cycle'],
    'Cross': ['cross', 'religion', 'faith', 'church', 'health'],

    // Productivity
    'CheckSquare': ['task', 'list', 'done', 'complete', 'box', 'todo'],
    'List': ['list', 'tasks', 'items', 'bullets', 'order'],
    'Calendar': ['calendar', 'date', 'day', 'month', 'year', 'agenda', 'plan', 'event'],
    'Clock': ['clock', 'time', 'hour', 'minute', 'alarm', 'delay', 'wait'],
    'Award': ['award', 'medal', 'achievement', 'winner', 'victory', 'recognition'],
    'Flag': ['flag', 'goal', 'mark', 'milestone', 'target', 'destination'],
    'Bookmark': ['bookmark', 'save', 'favorite', 'read', 'book'],
    'FileText': ['file', 'text', 'document', 'paper', 'note'],
    'Folder': ['folder', 'directory', 'files', 'organize', 'save'],
    'Archive': ['archive', 'box', 'save', 'history', 'old'],
    'Inbox': ['inbox', 'mail', 'receive', 'messages'],
    'Mail': ['mail', 'letter', 'email', 'message', 'envelope', 'send'],
    'Send': ['send', 'airplane', 'paper', 'message'],
    'Paperclip': ['paperclip', 'attachment', 'file', 'link'],
    'Pin': ['pin', 'thumbtack', 'fix', 'mark', 'location', 'note'],
    'Briefcase': ['briefcase', 'work', 'business', 'job', 'office', 'professional'],
    'Layers': ['layers', 'levels', 'stack', 'pile', 'organize'],
    'Rocket': ['rocket', 'launch', 'start', 'fast', 'space', 'boost', 'startup'],
    'Layout': ['layout', 'design', 'structure', 'grid', 'panel', 'organization'],
    'Kanban': ['kanban', 'board', 'columns', 'agile', 'tasks', 'project'],
    'ListTodo': ['tasks', 'pending', 'todo', 'list', 'checklist'],
    'Focus': ['focus', 'concentration', 'aim', 'center', 'attention'],
    'Compass': ['compass', 'direction', 'guide', 'orientation', 'path', 'north'],
    'Hourglass': ['hourglass', 'time', 'wait', 'countdown', 'duration'],
    'Wand2': ['wand', 'magic', 'auto', 'create', 'magic wand', 'tool'],
    'Workflow': ['workflow', 'process', 'steps', 'diagram', 'system'],

    // Finance
    'DollarSign': ['dollar', 'money', 'currency', 'cash', 'payment', 'price', 'cost'],
    'CreditCard': ['card', 'credit', 'debit', 'payment', 'buy', 'bank', 'plastic'],
    'Wallet': ['wallet', 'purse', 'money', 'save', 'payment', 'cash'],
    'PiggyBank': ['pig', 'savings', 'money', 'bank', 'save', 'piggy bank'],
    'Banknote': ['banknote', 'bill', 'money', 'cash', 'paper', 'payment'],
    'Coins': ['coins', 'money', 'change', 'loose', 'gold', 'silver'],
    'TrendingUp': ['trend', 'up', 'growth', 'rise', 'improvement', 'chart', 'progress'],
    'BarChart': ['chart', 'bars', 'data', 'statistics', 'analysis'],
    'PieChart': ['chart', 'pie', 'slice', 'percentage', 'data'],
    'ShoppingBag': ['bag', 'shopping', 'store', 'retail', 'market'],
    'ShoppingCart': ['cart', 'shopping', 'supermarket', 'store', 'ecommerce'],
    'Tag': ['tag', 'price', 'brand', 'category', 'name'],
    'Gift': ['gift', 'present', 'surprise', 'box', 'donation', 'birthday'],
    'Percent': ['percent', 'discount', 'offer', 'sale', 'rate'],
    'Receipt': ['receipt', 'invoice', 'ticket', 'payment', 'voucher', 'purchase'],
    'Calculator': ['calculator', 'math', 'add', 'accounts', 'numbers', 'accounting'],
    'Bitcoin': ['bitcoin', 'crypto', 'cryptocurrency', 'money', 'digital', 'investment'],
    'Vault': ['vault', 'safe', 'bank', 'save', 'protection'],
    'Building': ['building', 'company', 'corporation', 'bank', 'office'],
    'TrendingDown': ['trend', 'down', 'fall', 'decrease', 'loss', 'chart'],
    'Gavel': ['gavel', 'judge', 'law', 'justice', 'legal', 'auction'],

    // Technology
    'Smartphone': ['phone', 'mobile', 'cellphone', 'screen', 'call', 'app'],
    'Laptop': ['laptop', 'computer', 'pc', 'work', 'technology'],
    'Monitor': ['screen', 'monitor', 'computer', 'pc', 'display'],
    'Cpu': ['processor', 'chip', 'brain', 'hardware', 'computer'],
    'Wifi': ['wifi', 'internet', 'connection', 'network', 'signal', 'wireless'],
    'Battery': ['battery', 'energy', 'charge', 'power'],
    'Bluetooth': ['bluetooth', 'connection', 'wireless', 'device', 'pair'],
    'Headphones': ['headphones', 'music', 'listen', 'audio', 'sound'],
    'Code': ['code', 'program', 'development', 'software', 'html', 'tags'],
    'Terminal': ['console', 'terminal', 'commands', 'code', 'program', 'cmd'],
    'Database': ['database', 'server', 'storage', 'data', 'sql'],
    'Server': ['server', 'network', 'hosting', 'computer', 'data'],
    'Cloud': ['cloud', 'internet', 'storage', 'online', 'weather'],
    'Keyboard': ['keyboard', 'type', 'keys', 'computer', 'pc'],
    'Mouse': ['mouse', 'click', 'computer', 'pc', 'pointer'],
    'Gamepad': ['gamepad', 'game', 'console', 'videogame', 'play', 'gamer'],
    'Bot': ['robot', 'bot', 'AI', 'intelligence', 'machine', 'automaton'],
    'Fingerprint': ['fingerprint', 'security', 'biometrics', 'identity', 'touch'],

    // Education
    'Book': ['book', 'read', 'study', 'reading', 'learn', 'novel'],
    'BookOpen': ['open book', 'read', 'study', 'learn', 'education'],
    'GraduationCap': ['graduation', 'university', 'school', 'college', 'study', 'degree'],
    'Library': ['library', 'books', 'study', 'read', 'building', 'learn'],
    'Pencil': ['pencil', 'write', 'draw', 'note', 'eraser'],
    'Pen': ['pen', 'write', 'sign', 'ink'],
    'Lightbulb': ['lightbulb', 'idea', 'light', 'think', 'creation', 'innovation', 'inspiration'],
    'Puzzle': ['puzzle', 'game', 'piece', 'solution', 'logic', 'fit'],
    'BrainCircuit': ['brain', 'intelligence', 'AI', 'technology', 'mind', 'think'],
    'School': ['school', 'college', 'building', 'study', 'learn', 'education'],
    'Microscope': ['microscope', 'science', 'research', 'laboratory', 'biology'],
    'Telescope': ['telescope', 'stars', 'space', 'science', 'observe', 'astronomy'],
    'Atom': ['atom', 'science', 'physics', 'chemistry', 'nucleus', 'electron'],
    'Backpack': ['backpack', 'bag', 'school', 'travel', 'carry', 'luggage'],
    'Languages': ['languages', 'speak', 'translation', 'words', 'communication'],
    'Palette': ['palette', 'paint', 'art', 'colors', 'drawing', 'creative'],
    'Ruler': ['ruler', 'measure', 'math', 'geometry', 'drawing', 'size'],
    'FileBadge': ['certificate', 'diploma', 'achievement', 'file', 'award', 'document'],
    'BookMarked': ['bookmarked', 'study', 'bookmark', 'read', 'learn'],

    // Home
    'Home': ['house', 'home', 'building', 'residence', 'start'],
    'Key': ['key', 'lock', 'door', 'open', 'security', 'access'],
    'Lock': ['padlock', 'locked', 'safe', 'private', 'password'],
    'Unlock': ['open', 'unlocked', 'padlock', 'access', 'free'],
    'DoorOpen': ['door', 'open', 'enter', 'exit', 'room', 'house'],
    'Sofa': ['sofa', 'couch', 'furniture', 'rest', 'living room', 'seat'],
    'BedDouble': ['bed', 'double', 'sleep', 'couple', 'room', 'rest'],
    'Bath': ['bathtub', 'bath', 'shower', 'water', 'clean', 'wash'],
    'Utensils': ['cutlery', 'fork', 'knife', 'food', 'eat', 'restaurant', 'kitchen'],
    'Wine': ['wine', 'glass', 'drink', 'alcohol', 'party', 'celebration', 'toast'],
    'ChefHat': ['chef', 'cook', 'hat', 'kitchen', 'recipe', 'food'],
    'Wrench': ['wrench', 'tool', 'repair', 'fix', 'mechanic', 'workshop'],
    'Hammer': ['hammer', 'tool', 'hit', 'nail', 'construction', 'fix'],
    'Umbrella': ['umbrella', 'rain', 'weather', 'water', 'protect'],
    'Scissors': ['scissors', 'cut', 'paper', 'tool', 'hairdresser', 'craft'],
    'Plant': ['plant', 'leaf', 'nature', 'grow', 'green', 'garden', 'pot'],
    'Trash': ['trash', 'bin', 'delete', 'waste', 'clean', 'garbage'],
    'BedSingle': ['single bed', 'sleep', 'rest', 'dream', 'room'],
    'CoffeeMaker': ['coffee maker', 'machine', 'coffee', 'breakfast', 'kitchen', 'drink'],
    'Blinds': ['blinds', 'curtains', 'window', 'light', 'shade', 'house'],

    // Food
    'Banana': ['banana', 'fruit', 'food', 'diet', 'potassium'],
    'Cherry': ['cherry', 'fruit', 'food', 'sweet', 'red', 'dessert'],
    'Citrus': ['citrus', 'lemon', 'orange', 'fruit', 'acid', 'juice', 'vitamin'],
    'Croissant': ['croissant', 'bread', 'breakfast', 'food', 'bakery', 'sweet'],
    'Grape': ['grape', 'fruit', 'food', 'wine', 'bunch'],
    'IceCream': ['ice cream', 'dessert', 'sweet', 'cold', 'summer', 'food'],
    'NutOff': ['nut', 'allergy', 'nuts', 'food', 'health', 'caution'],
    'Pizza': ['pizza', 'food', 'junk', 'italian', 'cheese', 'slice'],
    'Beer': ['beer', 'drink', 'alcohol', 'bar', 'party', 'beverage'],
    'CupSoda': ['soda', 'soft drink', 'drink', 'cup', 'ice', 'straw', 'food'],
    'Martini': ['martini', 'cocktail', 'drink', 'alcohol', 'party', 'bar', 'beverage'],
    'Beef': ['beef', 'meat', 'steak', 'protein', 'food', 'roast'],
    'Cake': ['cake', 'pie', 'birthday', 'sweet', 'dessert', 'celebration'],
    'UtensilsCrossed': ['cutlery', 'restaurant', 'eat', 'dine', 'food', 'crossed'],

    // Travel
    'Plane': ['airplane', 'plane', 'flight', 'travel', 'air', 'airport', 'fly'],
    'Car': ['car', 'vehicle', 'drive', 'travel', 'motor'],
    'Bus': ['bus', 'transport', 'public', 'travel', 'route'],
    'Train': ['train', 'railway', 'travel', 'track', 'station', 'transport'],
    'Ship': ['ship', 'boat', 'sea', 'water', 'sail', 'travel', 'cruise'],
    'Map': ['map', 'direction', 'route', 'path', 'guide', 'location'],
    'MapPin': ['pin', 'location', 'place', 'marker', 'destination', 'map'],
    'Globe': ['globe', 'world', 'earth', 'planet', 'international', 'countries'],
    'Luggage': ['luggage', 'suitcase', 'travel', 'vacation', 'bag', 'carry'],
    'Ticket': ['ticket', 'entry', 'cinema', 'concert', 'travel', 'pass'],
    'Camera': ['camera', 'photo', 'photography', 'image', 'capture', 'lens'],
    'Image': ['image', 'photo', 'landscape', 'picture', 'gallery', 'visual'],
    'Mountain': ['mountain', 'nature', 'peak', 'climb', 'landscape', 'rock'],
    'Tent': ['tent', 'camp', 'camping', 'nature', 'sleep', 'outside'],
    'Hotel': ['hotel', 'building', 'lodging', 'sleep', 'travel', 'vacation'],
    'TrainFront': ['train', 'metro', 'subway', 'travel', 'transport', 'public'],
    'BusFront': ['bus', 'coach', 'transport', 'public', 'travel', 'route'],
    'CarTaxiFront': ['taxi', 'car', 'auto', 'travel', 'transport', 'passenger'],

    // Nature
    'TreePine': ['pine', 'tree', 'forest', 'nature', 'wood', 'plant'],
    'TreeDeciduous': ['tree', 'leaves', 'nature', 'forest', 'plant', 'green'],
    'Trees': ['trees', 'forest', 'nature', 'park', 'landscape', 'plants'],
    'Leaf': ['leaf', 'nature', 'plant', 'green', 'autumn', 'ecology'],
    'Flower': ['flower', 'nature', 'plant', 'spring', 'petal', 'garden'],
    'Flower2': ['flower', 'rose', 'nature', 'plant', 'garden', 'decoration'],
    'CloudSun': ['cloud', 'sun', 'weather', 'time', 'sky', 'partly cloudy'],
    'CloudRain': ['rain', 'cloud', 'water', 'weather', 'time', 'storm'],
    'Snowflake': ['snow', 'flake', 'cold', 'winter', 'ice', 'freeze'],
    'Wind': ['wind', 'air', 'weather', 'breeze', 'storm', 'blow'],
    'MountainSnow': ['mountain', 'snow', 'peak', 'climb', 'winter', 'nature'],
    'SunMedium': ['sun', 'heat', 'shine', 'day', 'weather', 'light'],
    'MoonStar': ['moon', 'star', 'night', 'sky', 'sleep', 'space'],
    'Bird': ['bird', 'fly', 'animal', 'pet', 'nature'],
    'Bug': ['bug', 'insect', 'error', 'animal', 'nature', 'small'],
    'Fish': ['fish', 'water', 'sea', 'ocean', 'animal', 'swim'],
    'Rabbit': ['rabbit', 'bunny', 'animal', 'pet', 'jump', 'fast', 'carrot'],
    'Snail': ['snail', 'slow', 'animal', 'bug', 'shell'],
    'Turtle': ['turtle', 'slow', 'animal', 'sea', 'water', 'shell'],
    'Worm': ['worm', 'earthworm', 'earth', 'animal', 'bug'],

    // Sports
    'Medal': ['medal', 'prize', 'winner', 'victory', 'achievement', 'competition'],
    'Swords': ['swords', 'fight', 'combat', 'game', 'battle', 'duel'],
    'Goal': ['goal', 'score', 'soccer', 'target', 'points', 'sport'],

    // Social
    'User': ['user', 'person', 'profile', 'account', 'avatar', 'human'],
    'Users': ['users', 'people', 'group', 'team', 'community', 'friends'],
    'UserPlus': ['add', 'user', 'friend', 'invite', 'new', 'follow'],
    'MessageCircle': ['message', 'chat', 'talk', 'comment', 'bubble', 'text'],
    'MessageSquare': ['message', 'chat', 'square', 'text', 'comment', 'talk'],
    'Phone': ['phone', 'call', 'mobile', 'contact', 'talk', 'voice'],
    'Video': ['video', 'camera', 'record', 'movie', 'meeting', 'call'],
    'Mic': ['microphone', 'mic', 'voice', 'record', 'audio', 'talk', 'sing', 'podcast'],
    'Music': ['music', 'note', 'sound', 'song', 'listen', 'audio', 'melody'],
    'Share2': ['share', 'network', 'send', 'broadcast', 'connect', 'link'],
    'ThumbsUp': ['like', 'good', 'approve', 'thumb', 'positive'],
    'HeartHandshake': ['heart', 'hands', 'agreement', 'deal', 'friendship', 'help', 'support'],
    'PartyPopper': ['party', 'celebration', 'confetti', 'joy', 'event', 'birthday'],
    'Baby': ['baby', 'child', 'infant', 'son', 'parenting', 'small'],
    'Bell': ['bell', 'notification', 'alert', 'warning', 'sound', 'ring'],
    'Cat': ['cat', 'pet', 'animal', 'feline'],
    'Dog': ['dog', 'pet', 'animal', 'canine', 'puppy'],
    'Gamepad2': ['game', 'videogame', 'console', 'controller', 'play', 'gamer'],
    'ThumbsDown': ['dislike', 'bad', 'disapprove', 'thumb', 'negative'],
    'HandMetal': ['hand', 'metal', 'rock', 'music', 'concert', 'horns'],
    'Handshake': ['handshake', 'deal', 'agreement', 'business', 'greeting', 'peace']
};
